services:
  backend:
    environment:
      POSTGRESQL_DATABASE: stoorage_db
      POSTGRESQL_USERNAME: stoorage
      POSTGRESQL_PASSWORD: 123
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/app/__pycache__

  database:
    hostname: database
    image: bitnamilegacy/postgresql:14.11.0
    environment:
      POSTGRESQL_DATABASE: stoorage_db
      POSTGRESQL_USERNAME: stoorage
      POSTGRESQL_PASSWORD: 123
      POSTGRESQL_TIMEZONE: America/Sao_Paulo
      POSTGRESQL_LOG_TIMEZONE: America/Sao_Paulo
    volumes:
      - postgres_data:/bitnami/postgresql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
