
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENV: ${ENV:-development}
    restart: always
    volumes:
      - ./backend/app/:/backend/app/
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENV:-development}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
